sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="containerd"
  - DOCKER_HUB_ORG="daffa99"
before_install:
- openssl aes-256-cbc -K $encrypted_458ea1839440_key -iv $encrypted_458ea1839440_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_7cbe93117c56_key -iv $encrypted_7cbe93117c56_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy_rsa
after_script:
- sed -i "s/os.getenv('BASE_URL')/'${BASE_URL}'/g" endpoint.py
- sed -i "s/os.getenv('LINE_CHANNEL_SECRET', None)/'${LINE_CHANNEL_SECRET}'/g" app.py
- sed -i "s/os.getenv('LINE_CHANNEL_ACCESS_TOKEN', None)/'${LINE_CHANNEL_ACCESS_TOKEN}'/g"
  app.py
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:tukulsaBOT-${TRAVIS_BUILD_ID}
  .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:tukulsaBOT-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:tukulsaBOT-${TRAVIS_BUILD_ID}
  ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:BOT
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:BOT
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh
deploy:
- true: 
  branches:
    only:
    - deploy-aws
